---
- name: Download package
  get_url:
    url: https://nodejs.org/dist/{{ nodejs_version }}/node-{{ nodejs_version }}-linux-x64.tar.xz
    force: no
    dest: /tmp/node-{{ nodejs_version }}-linux-x64.tar.gz

- name: Create install directory
  file:
    state: directory
    dest: "{{ nodejs_prefix }}"

- name: Unpack the package
  unarchive:
    remote_src: yes
    src: /tmp/node-{{ nodejs_version }}.tar.gz
    dest: "{{ nodejs_prefix }}"

- name: Create symlinks
  file:
    src: "{{ nodejs_prefix }}/node-{{ nodejs_version }}-linux-x64/bin/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
    - node
    - npm
    - npx
