---
- name: Install MySQL version 5.6
  yum: name={{ item }}
  with_items:
    - mysql56
    - mysql56-common
    - mysql56-devel
    - mysql56-libs
    - mysql56-server

- name: Install a python module (needed by ansible)
  yum: name=MySQL-python

- name: Install a python module (needed by ansible)
  yum: name={{ item }}
  with_items:
    - MySQL-python26
    - MySQL-python27
  when: ansible_distribution == 'Amazon' # Amazon Linux AMI

- name: Make a log directory
  file: state=directory path={{ mysql56_aws_log_dir }} owner=mysql group=mysql mode=0775

- name: Copy my.conf
  template: src=my.cnf dest=/etc/my.cnf owner=root group=root mode=0644
  notify:
    - Restart mysqld

- name: logrotation
  template: src={{ item }} dest=/etc/logrotate.d/{{ item }} owner=root group=root mode=0644
  with_items:
    - mysql_log

- name: Auto start MySQL
  service: name=mysqld state=started enabled=yes
