---
- name: Install Tomcat6
  yum: name={{ item }}
  with_items:
    - tomcat6
    - tomcat6-el-2.1-api
    - tomcat6-jsp-2.1-api
    - tomcat6-servlet-2.5-api
    - tomcat6-lib

- name: Enable tomcat6
  service: name=tomcat6 state=started enabled=yes
