---
- name: Install the latest MySQL
  include: mysql.yml
  when: mysql_version is not defined

- name: Install MySQL 5.5
  include: mysql55.yml
  when: mysql_version is defined and mysql_version == 5.5

- name: Install MySQL 5.6
  include: mysql56.yml
  when: mysql_version is defined and mysql_version == 5.6

- name: Creates log directory
  file: path=/var/log/mysql/ state=directory owner=mysql group=mysql mode=775

- name: Install python module (needed by ansible)
  yum: name=MySQL-python

- name: Install python module (needed by ansible)
  yum: name={{ item }}
  with_items:
    - MySQL-python26
    - MySQL-python27
  when: ansible_distribution == 'Amazon' # Amazon Linux AMI

- name: Load a variables file
  include_vars: "{{ item }}"
  with_first_found:
    - ../vars/mysql{{ mysql_version }}.yml
    - ../vars/mysql.yml

- name: Copy my.conf
  template: src={{ mysql_template_my_cnf }} dest=/etc/my.cnf owner=root group=root mode=0644
  notify:
    - Restart mysqld

- name: logrotation
  copy: src={{ item }} dest=/etc/logrotate.d/{{ item }} owner=root group=root mode=0644
  with_items:
    - mysql_log
    - mysql_backup

- name: Auto start MySQL
  service: name=mysqld state=running enabled=yes

