---
- name: Install the Yum repository for MySQL community version
  yum: name={{ mysql_community_yum_repo }}

- name: Install the MySQL-5.6 packages
  yum: name={{ item }} enablerepo=mysql56-community disablerepo=mysql57-community state=present
  with_items:
    # Install multiple packages at once (comma separated list)
    - mysql-community-server-5.6.27,mysql-community-libs-5.6.27,mysql-community-common-5.6.27,mysql-community-devel-5.6.27,mysql-community-client-5.6.27

