---
- name: Install a yum repository for MySQL community version
  yum: name={{ item }}
  with_items:
    - http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm

- name: Install the MySQL 5.7 packages
  yum: name={{ item }} state=present enablerepo=mysql57-community
  with_items:
    - mysql-community-server
    - mysql-community-libs
    - mysql-community-common
    - mysql-community-devel
    - mysql-community-client

- name: Install python module (needed by ansible)
  yum: name=MySQL-python

- name: Install python module (needed by ansible)
  yum: name={{ item }}
  with_items:
    - MySQL-python26
    - MySQL-python27
  when: ansible_distribution == 'Amazon' # Amazon Linux AMI

- name: Make a log directory
  file: state=directory path={{ mysql57_community_log_dir } owner=mysql group=mysql mode=0775

- name: Copy my.conf
  template: src=my.cnf dest=/etc/my.cnf owner=root group=root mode=0644
  notify:
    - Restart mysqld

- name: logrotation
  copy: src={{ item }} dest=/etc/logrotate.d/{{ item }} owner=root group=root mode=0644
  with_items:
    - mysql_log

- name: Auto start MySQL
  service: name=mysqld state=started enabled=yes

- name: Capture root password
  shell: 'sed -ne "s/.*root@localhost: \(.[^ ]*\)/\1/p" /var/log/mysql/mysqld.log'
  become: yes
  register: mysql57_centos_root_password

- name: root password
  debug: msg={{ mysql57_centos_root_password.stdout }}

- name: Clear root password
  mysql_user: name=root host=localhost password='' login_user=root login_password={{ mysql57_centos_root_password.stdout }}

