---
- name: Install yum repos for PostgreSQL 9.3
  yum: name={{ item }}
  with_items:
    - http://yum.postgresql.org/9.3/redhat/rhel-6-x86_64/pgdg-redhat93-9.3-1.noarch.rpm

- name: Install PostgreSQL 9.3
  yum: name={{ item }}
  with_items:
    - postgresql93
    - postgresql93-server
    - postgresql93-contrib

