---
- name: Install dependency libraries
  yum: name={{ item }}
  with_items:
    - openssl
    - openssl-devel
    - expat
    - expat-devel
    - libcurl
    - libcurl-devel
    - gettext
    - perl-ExtUtils-MakeMaker

- name: Install Git (Git is needed to install Git...)
  yum: name=git

- name: Clone Git repository
  git:
    repo: 'https://github.com/git/git'
    dest: /usr/local/src/git
    version: "{{ git_version }}"

- name: make
  make:
    chdir: /usr/local/src/git
    params:
      prefix: /usr/local

- name: make install
  make:
    chdir: /usr/local/src/git
    target: install
    params:
      prefix: /usr/local
