- name: Install yum repos
  yum: name={{ item }}
  with_items:
    - http://repo.zabbix.com/zabbix/2.0/rhel/6/x86_64/zabbix-release-2.0-1.el6.noarch.rpm

- name: Install all packages
  yum: name={{ item }}
  with_items:
    - zabbix-agent

- name: Copy zabbix-agentd.conf
  template: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf
  notify:
    - Restart Zabbix

- name: Auto start zabbix-agentd
  service: name=zabbix-agent state=running enabled=yes
