---
- name: Installs Go
  yum: name=golang

- name: Set $GOPATH
  lineinfile: dest=~/.bash_profile state=present regexp='^export GOPATH' line="export GOPATH={{ golang_gopath }}"

- name: Set $PATH
  lineinfile: dest=~/.bash_profile state=present regexp='^export PATH=\$GOPATH/bin' line="export PATH=$GOPATH/bin:$PATH"

